server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coffee_shop
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    hibernate:
    #      ddl-auto: create
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
#      hibernate:
#        format_sql: true
    open-in-view: false

  flyway:
    locations: classpath:db.migration
    baseline-on-migrate: true



# To list any process listening to the port 8080:
# lsof -i:8080


# brew services stop postgresql@15

# PostgreSQL 16
# pass root