spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: jdbc:mysql://localhost:3306/dictionary?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
  thymeleaf: # Thymeleaf
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    # prefix: file:src/main/resources/templates/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    hidden-method:
      filter:
        enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080