spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gira?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #    hibernate:
    #      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    schemas: gira
    user: root
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true