spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: jdbc:mysql://localhost:3306/bonappetit?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml
  thymeleaf: # Thymeleaf
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    # prefix: file:src/main/resources/templates/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: false
  mvc:
    hidden-method:
      filter:
        enabled: true
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor: TRACE
#        SQL: DEBUG
#      nodeValue: WARN
#    blog: WARN
server:
  port: 8080