server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/like_book
    username: andreystoev
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true